import type { Prisma } from "@prisma/client";

type CareerSeed = Omit<Prisma.CareerDestinationCreateInput, "id">;

const REAL_COMPANY_PATTERNS = [
  /삼성|samsung/i,
  /현대|hyundai/i,
  /엘지|lg/i,
  /sk\b/i,
  /네이버|naver/i,
  /카카오|kakao/i,
  /쿠팡|coupang/i,
  /배달의민족|baedal/i,
  /토스|toss/i,
  /구글|google\b/i,
  /애플|apple\s/i,
  /메타|meta\b|facebook/i,
  /아마존|amazon/i,
  /마이크로소프트|microsoft/i,
  /테슬라|tesla/i,
  /인텔|intel/i,
  /도요타|toyota/i,
  /코카콜라|coca.cola/i,
  /맥도날드|mcdonald/i,
  /나이키|nike\b/i,
  /에스케이|sk\s/i,
];

const CONTROVERSY_PATTERNS = [
  /실제.*논란/i,
  /실제.*의혹/i,
  /실제.*사건/i,
  /진짜.*회사/i,
  /실제.*인물/i,
  /inspiredBy/i,
  /inspired.by/i,
];

export function validateCareerDestination(seed: CareerSeed): string[] {
  const errors: string[] = [];
  const combinedName = seed.displayName;

  for (const pattern of REAL_COMPANY_PATTERNS) {
    if (pattern.test(combinedName)) {
      errors.push(`displayName "${seed.displayName}" resembles real company: ${pattern}`);
    }
  }

  const tags = (seed.cultureTags as string[]) ?? [];
  const allText = [combinedName, seed.industry, ...tags].join(" ");
  for (const pattern of CONTROVERSY_PATTERNS) {
    if (pattern.test(allText)) {
      errors.push(`Contains real-reference pattern: ${pattern}`);
    }
  }

  const allowedTypes = [
    "PARODY_COMPANY",
    "PUBLIC_SECTOR",
    "LICENSED_PROFESSION",
    "ENTREPRENEURSHIP",
    "SELF_EMPLOYMENT",
  ];

  if (!allowedTypes.includes(seed.destinationType)) {
    errors.push(`Invalid destinationType: ${seed.destinationType}`);
  }

  if (seed.hiringDifficulty < 1 || seed.hiringDifficulty > 5) {
    errors.push("hiringDifficulty must be 1-5");
  }

  return errors;
}

export function seedCareerDestinations(): CareerSeed[] {
  return [
    {
      displayName: "한강물류",
      destinationType: "PARODY_COMPANY",
      industry: "물류/유통",
      roles: ["물류 기획", "창고 관리", "배송 라우팅"],
      salaryBand: "2800~3500만원",
      cultureTags: ["빠른 템포", "야근 많음", "식대 지원"],
      hiringDifficulty: 2,
      preferredStats: { practical: 60, health: 50 },
      eventTone: ["실무 중심", "목표 지향"],
    },
    {
      displayName: "다온소프트",
      destinationType: "PARODY_COMPANY",
      industry: "IT/소프트웨어",
      roles: ["주니어 개발", "QA 테스터", "기술문서 작성"],
      salaryBand: "3200~4500만원",
      cultureTags: ["수평적", "자율 출퇴근", "스타트업 분위기"],
      hiringDifficulty: 3,
      preferredStats: { practical: 55, creativity: 50 },
      eventTone: ["협업", "도전적"],
    },
    {
      displayName: "서리울건축",
      destinationType: "PARODY_COMPANY",
      industry: "건축/설계",
      roles: ["설계 보조", "현장 관리", "견적 작성"],
      salaryBand: "3000~4000만원",
      cultureTags: ["전통적", "조직적", "현장 중심"],
      hiringDifficulty: 3,
      preferredStats: { practical: 55, academic: 45 },
      eventTone: ["체계적", "보수적"],
    },
    {
      displayName: "푸른들식품",
      destinationType: "PARODY_COMPANY",
      industry: "식품/제조",
      roles: ["품질 관리", "마케팅", "영업 지원"],
      salaryBand: "2600~3400만원",
      cultureTags: ["안정적", "워라밸 좋음", "복지 우수"],
      hiringDifficulty: 2,
      preferredStats: { health: 45, communication: 50 },
      eventTone: ["온화한", "친근한"],
    },
    {
      displayName: "미래교육연구소",
      destinationType: "PARODY_COMPANY",
      industry: "교육/연구",
      roles: ["교육 콘텐츠 개발", "연구 보조", "프로그램 기획"],
      salaryBand: "2800~3800만원",
      cultureTags: ["지적 자극", "연구 중심", "유연 근무"],
      hiringDifficulty: 3,
      preferredStats: { academic: 60, creativity: 45 },
      eventTone: ["학구적", "협력적"],
    },
    {
      displayName: "청년신문",
      destinationType: "PARODY_COMPANY",
      industry: "미디어/언론",
      roles: ["기자", "콘텐츠 에디터", "소셜미디어 관리"],
      salaryBand: "2500~3600만원",
      cultureTags: ["빠른 변화", "창의성 중시", "네트워크 중요"],
      hiringDifficulty: 3,
      preferredStats: { communication: 65, creativity: 50 },
      eventTone: ["다이나믹", "시사적"],
    },
    {
      displayName: "동그라미광고",
      destinationType: "PARODY_COMPANY",
      industry: "광고/마케팅",
      roles: ["카피라이터", "AD 기획", "마케팅 데이터 분석"],
      salaryBand: "3000~4200만원",
      cultureTags: ["창의성 중시", "자유로운 분위기", "야근 있음"],
      hiringDifficulty: 4,
      preferredStats: { creativity: 65, communication: 55 },
      eventTone: ["창의적", "열정적"],
    },
    {
      displayName: "서울시청(가상)",
      destinationType: "PUBLIC_SECTOR",
      industry: "공공행정",
      roles: ["행정직", "민원 대응", "정책 보조"],
      salaryBand: "2700~4000만원",
      cultureTags: ["안정적", "체계적", "워라밸 우수"],
      hiringDifficulty: 4,
      preferredStats: { academic: 55, communication: 45 },
      eventTone: ["안정적", "공공성"],
    },
    {
      displayName: "가칭교육청",
      destinationType: "PUBLIC_SECTOR",
      industry: "공공교육",
      roles: ["교육 행정", "시설 관리", "프로그램 코디"],
      salaryBand: "2600~3800만원",
      cultureTags: ["안정적", "공공성", "워라밸 좋음"],
      hiringDifficulty: 3,
      preferredStats: { academic: 50, communication: 45 },
      eventTone: ["안정적", "공익적"],
    },
    {
      displayName: "변호사(가상 법률사무소)",
      destinationType: "LICENSED_PROFESSION",
      industry: "법률",
      roles: ["변호사", "법률 연구원", "소송 사무"],
      salaryBand: "5000~12000만원",
      cultureTags: ["전문적", "고압적", "수익성 높음"],
      hiringDifficulty: 5,
      preferredStats: { academic: 75, communication: 60 },
      eventTone: ["전문적", "도전적"],
    },
    {
      displayName: "가상회계법인",
      destinationType: "LICENSED_PROFESSION",
      industry: "회계/세무",
      roles: ["공인회계사", "세무사", "회계 관리"],
      salaryBand: "4000~8000만원",
      cultureTags: ["전문적", "정확성 중시", "시즌 집중"],
      hiringDifficulty: 5,
      preferredStats: { academic: 70, practical: 55 },
      eventTone: ["정밀함", "체계적"],
    },
    {
      displayName: "의사(가상병원)",
      destinationType: "LICENSED_PROFESSION",
      industry: "의료",
      roles: ["전문의", "인턴", "의료 연구"],
      salaryBand: "6000~15000만원",
      cultureTags: ["고강도", "사회적 기여", "높은 전문성"],
      hiringDifficulty: 5,
      preferredStats: { academic: 80, health: 60 },
      eventTone: ["책임감", "긴박감"],
    },
    {
      displayName: "작은가게 창업",
      destinationType: "ENTREPRENEURSHIP",
      industry: "소매/외식",
      roles: ["사장", "운영 관리"],
      salaryBand: "가변적 (1500~6000만원)",
      cultureTags: ["주도적", "리스크 있음", "자유도 높음"],
      hiringDifficulty: 2,
      preferredStats: { practical: 50, wealth: 30 },
      eventTone: ["도전적", "독립적"],
    },
    {
      displayName: "프리랜서 웹디자인",
      destinationType: "SELF_EMPLOYMENT",
      industry: "디자인/IT",
      roles: ["웹디자이너", "UI/UX 기획", "프리랜서"],
      salaryBand: "가변적 (2000~5000만원)",
      cultureTags: ["자유로운", "불규칙", "포트폴리오 중요"],
      hiringDifficulty: 2,
      preferredStats: { creativity: 60, practical: 45 },
      eventTone: ["자유분방", "개인적"],
    },
    {
      displayName: "은빛컨설팅",
      destinationType: "PARODY_COMPANY",
      industry: "경영컨설팅",
      roles: ["리서치 애널리스트", "컨설턴트", "데이터 분석"],
      salaryBand: "3500~5500만원",
      cultureTags: ["스마트", "야근 많음", "성과급"],
      hiringDifficulty: 4,
      preferredStats: { academic: 60, communication: 60, practical: 50 },
      eventTone: ["전문적", "경쟁적"],
    },
    {
      displayName: "솔빛은행",
      destinationType: "PARODY_COMPANY",
      industry: "금융/은행",
      roles: ["창구 업무", "대출 심사", "리스크 관리"],
      salaryBand: "3000~4500만원",
      cultureTags: ["전통적", "안정적", "상여금"],
      hiringDifficulty: 3,
      preferredStats: { academic: 55, practical: 45 },
      eventTone: ["보수적", "체계적"],
    },
    {
      displayName: "초록숲환경",
      destinationType: "PARODY_COMPANY",
      industry: "환경/에너지",
      roles: ["환경 영향 평가", "ESG 보고", "커뮤니케이션"],
      salaryBand: "2800~4000만원",
      cultureTags: ["사명감", "미래 지향", "협력적"],
      hiringDifficulty: 3,
      preferredStats: { academic: 50, communication: 50 },
      eventTone: ["사명감", "협업"],
    },
    {
      displayName: "나래항공",
      destinationType: "PARODY_COMPANY",
      industry: "항공/운송",
      roles: ["객실 승무", "운항 관리", "고객 서비스"],
      salaryBand: "3000~5000만원",
      cultureTags: ["서비스 중심", "글로벌", "체력 중요"],
      hiringDifficulty: 4,
      preferredStats: { communication: 60, health: 55, charm: 50 },
      eventTone: ["서비스", "체계적"],
    },
    {
      displayName: "온누리호텔",
      destinationType: "PARODY_COMPANY",
      industry: "호텔/관광",
      roles: ["프론트 데스크", "객실 관리", "이벤트 기획"],
      salaryBand: "2600~3800만원",
      cultureTags: ["서비스 중심", "교대 근무", "팁 문화"],
      hiringDifficulty: 2,
      preferredStats: { communication: 55, charm: 50 },
      eventTone: ["친절", "바쁨"],
    },
    {
      displayName: "미소보험",
      destinationType: "PARODY_COMPANY",
      industry: "보험",
      roles: ["보상 심사", "언더라이팅", "고객 관리"],
      salaryBand: "2800~4000만원",
      cultureTags: ["안정적", "교육 체계", "성과급"],
      hiringDifficulty: 2,
      preferredStats: { communication: 50, practical: 45 },
      eventTone: ["안정", "일상적"],
    },
    {
      displayName: "모두의병원",
      destinationType: "PARODY_COMPANY",
      industry: "의료/헬스케어",
      roles: ["행정직", "의무 기록", "환자 상담"],
      salaryBand: "2500~3500만원",
      cultureTags: ["사명감", "교대 근무", "복지 좋음"],
      hiringDifficulty: 2,
      preferredStats: { academic: 45, communication: 50 },
      eventTone: ["사명감", "조용한"],
    },
    {
      displayName: "별밤레코드",
      destinationType: "PARODY_COMPANY",
      industry: "엔터테인먼트/음악",
      roles: ["A&R", "마케팅", "콘텐츠 기획"],
      salaryBand: "2400~4000만원",
      cultureTags: ["창의성", "자유로운", "비정기 근무"],
      hiringDifficulty: 4,
      preferredStats: { creativity: 65, communication: 50 },
      eventTone: ["예술적", "열정적"],
    },
    {
      displayName: "한국패션협회(가상)",
      destinationType: "PUBLIC_SECTOR",
      industry: "문화/패션",
      roles: ["기획", "행사 운영", "국제 협력"],
      salaryBand: "2600~3800만원",
      cultureTags: ["문화적", "네트워크", "공공성"],
      hiringDifficulty: 3,
      preferredStats: { creativity: 50, communication: 55 },
      eventTone: ["문화적", "협력적"],
    },
    {
      displayName: "푸른언론재단",
      destinationType: "PUBLIC_SECTOR",
      industry: "미디어/재단",
      roles: ["프로그램 매니저", "조사 연구", "커뮤니케이션"],
      salaryBand: "2800~4000만원",
      cultureTags: ["공익적", "연구 중심", "자율적"],
      hiringDifficulty: 3,
      preferredStats: { academic: 50, communication: 55 },
      eventTone: ["공익적", "안정적"],
    },
    {
      displayName: "약사(가상약국)",
      destinationType: "LICENSED_PROFESSION",
      industry: "제약/헬스케어",
      roles: ["약사", "의약품 관리", "건강 상담"],
      salaryBand: "4500~8000만원",
      cultureTags: ["전문적", "지역 사회", "안정적"],
      hiringDifficulty: 5,
      preferredStats: { academic: 70, communication: 50 },
      eventTone: ["전문적", "안정적"],
    },
    {
      displayName: "심리상담소 창업",
      destinationType: "ENTREPRENEURSHIP",
      industry: "헬스케어/상담",
      roles: ["상담사", "운영자"],
      salaryBand: "가변적 (2000~6000만원)",
      cultureTags: ["자율적", "사명감", "수요 증가"],
      hiringDifficulty: 3,
      preferredStats: { mental: 65, communication: 60 },
      eventTone: ["치유적", "독립적"],
    },
    {
      displayName: "IT 프리랜서 개발",
      destinationType: "SELF_EMPLOYMENT",
      industry: "IT",
      roles: ["프론트엔드 개발", "백엔드 개발", "풀스택"],
      salaryBand: "가변적 (3000~8000만원)",
      cultureTags: ["자유로운", "고소득 가능", "불안정"],
      hiringDifficulty: 2,
      preferredStats: { practical: 70, creativity: 50 },
      eventTone: ["자유분방", "도전적"],
    },
    {
      displayName: "마루건설",
      destinationType: "PARODY_COMPANY",
      industry: "건설/토목",
      roles: ["현장 관리", "안전 점검", "공정 관리"],
      salaryBand: "3200~4500만원",
      cultureTags: ["현장 중심", "체력 중요", "조직적"],
      hiringDifficulty: 2,
      preferredStats: { practical: 55, health: 55 },
      eventTone: ["현장감", "체계적"],
    },
    {
      displayName: "한결회계법인",
      destinationType: "PARODY_COMPANY",
      industry: "회계/세무",
      roles: ["회계 담당", "세무 신고", "감사 보조"],
      salaryBand: "3000~4200만원",
      cultureTags: ["정확성", "성수기 집중", "전문성"],
      hiringDifficulty: 3,
      preferredStats: { academic: 55, practical: 50 },
      eventTone: ["정밀함", "보수적"],
    },
    {
      displayName: "문화마당기획",
      destinationType: "PARODY_COMPANY",
      industry: "문화/이벤트",
      roles: ["이벤트 기획", "행사 운영", "홍보"],
      salaryBand: "2400~3500만원",
      cultureTags: ["창의성", "자유로운", "주말 근무"],
      hiringDifficulty: 2,
      preferredStats: { creativity: 55, communication: 55 },
      eventTone: ["창의적", "역동적"],
    },
    {
      displayName: "푸드트럭 운영",
      destinationType: "ENTREPRENEURSHIP",
      industry: "외식",
      roles: ["사장", "요리사"],
      salaryBand: "가변적 (1500~5000만원)",
      cultureTags: ["자유로운", "리스크 있음", "직접 운영"],
      hiringDifficulty: 1,
      preferredStats: { practical: 45, health: 40 },
      eventTone: ["도전적", "자유분방"],
    },
    {
      displayName: "번역 프리랜서",
      destinationType: "SELF_EMPLOYMENT",
      industry: "언어/번역",
      roles: ["번역가", "교정 교열", "로컬라이제이션"],
      salaryBand: "가변적 (2000~4500만원)",
      cultureTags: ["자유로운", "재택 근무", "불규칙"],
      hiringDifficulty: 2,
      preferredStats: { academic: 55, communication: 55 },
      eventTone: ["조용한", "개인적"],
    },
    {
      displayName: "사진작가 프리랜서",
      destinationType: "SELF_EMPLOYMENT",
      industry: "사진/영상",
      roles: ["사진작가", "영상 편집", "포트폴리오"],
      salaryBand: "가변적 (2000~6000만원)",
      cultureTags: ["창의적", "자유로운", "네트워크 중요"],
      hiringDifficulty: 2,
      preferredStats: { creativity: 65, practical: 40 },
      eventTone: ["예술적", "자유분방"],
    },
    {
      displayName: "라온데이터",
      destinationType: "PARODY_COMPANY",
      industry: "IT/데이터",
      roles: ["데이터 분석", "DB 관리", "리포트 작성"],
      salaryBand: "3200~4800만원",
      cultureTags: ["분석적", "성과급", "수평적"],
      hiringDifficulty: 3,
      preferredStats: { practical: 60, academic: 50 },
      eventTone: ["논리적", "협업"],
    },
    {
      displayName: "햇살복지재단",
      destinationType: "PUBLIC_SECTOR",
      industry: "사회복지",
      roles: ["사회복지사", "프로그램 기획", "모금 활동"],
      salaryBand: "2400~3400만원",
      cultureTags: ["사명감", "보람", "열악한 처우"],
      hiringDifficulty: 3,
      preferredStats: { mental: 55, communication: 55 },
      eventTone: ["사명감", "따뜻함"],
    },
    {
      displayName: "농수산물유통공사(가상)",
      destinationType: "PUBLIC_SECTOR",
      industry: "농업/유통",
      roles: ["유통 관리", "품질 검사", "지원 사업"],
      salaryBand: "2600~4000만원",
      cultureTags: ["안정적", "공공성", "지역 기반"],
      hiringDifficulty: 3,
      preferredStats: { practical: 50, academic: 45 },
      eventTone: ["안정적", "공익적"],
    },
    {
      displayName: "건축사(가상 사무소)",
      destinationType: "LICENSED_PROFESSION",
      industry: "건축",
      roles: ["건축사", "설계사", "감리"],
      salaryBand: "4000~8000만원",
      cultureTags: ["전문적", "창의적", "책임감"],
      hiringDifficulty: 5,
      preferredStats: { practical: 65, creativity: 60 },
      eventTone: ["전문적", "창의적"],
    },
    {
      displayName: "온라인쇼핑몰 창업",
      destinationType: "ENTREPRENEURSHIP",
      industry: "이커머스",
      roles: ["사장", "마케팅", "CS 관리"],
      salaryBand: "가변적 (1000~10000만원)",
      cultureTags: ["자유로운", "리스크 높음", "직접 운영"],
      hiringDifficulty: 1,
      preferredStats: { practical: 50, creativity: 50, wealth: 20 },
      eventTone: ["도전적", "독립적"],
    },
    {
      displayName: "영상 크리에이터",
      destinationType: "SELF_EMPLOYMENT",
      industry: "콘텐츠/미디어",
      roles: ["크리에이터", "편집자", "채널 운영"],
      salaryBand: "가변적 (0~무제한)",
      cultureTags: ["창의적", "자유로운", "불안정"],
      hiringDifficulty: 1,
      preferredStats: { creativity: 70, communication: 50 },
      eventTone: ["창의적", "자유분방"],
    },
    {
      displayName: "바이오연구소",
      destinationType: "PARODY_COMPANY",
      industry: "바이오/제약",
      roles: ["연구 보조", "실험 관리", "데이터 기록"],
      salaryBand: "3000~4200만원",
      cultureTags: ["연구 중심", "체계적", "인내심 필요"],
      hiringDifficulty: 4,
      preferredStats: { academic: 65, practical: 50 },
      eventTone: ["학구적", "정밀함"],
    },
  ];
}